---
###################
# Upgrade system
###################
- name: yum upgrade
  yum: name=* state=latest update_cache=yes

###################
# Misc. tools
###################
- name: Install usefull system tools with yum
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - nasm
    - ltrace
    - git
    - zsh
    - tmux
    - vim-minimal
    - ctags
    - cscope
    - htop
    - xz
    - elinks
    - curl
    - pam-devel
    - openssl-devel
    - libpcap-devel

- name: Install usefull system tools with yum on Fedora
  yum: name={{ item }} state=present
  with_items:
    - colorgcc
    - clang
    - tig
    - python3
    - bpython
  when: ansible_distribution == 'Fedora'
