---
# http://serverfault.com/questions/587727/how-to-unify-package-installation-tasks-in-ansible

- hosts: all
  remote_user: vagrant
  vars_files:
    - [ "vars/{{ ansible_distribution }}.yml", "vars/default.yml" ]
  vars:
    # Username
    user: vagrant
    rootkits:
        beurk:
            url: https://github.com/unix-thrust/beurk.git
            dest: ~/project/beurk
            version: dev
        azazel:
            url: https://github.com/chokepoint/azazel.git
            dest: ~/project/azazel
            version: master
    antirootkits:
        ossec:
            url: https://github.com/ossec/ossec-hids.git
            dest: ~/project/ossec
            version: stable
    install_selinux: false
    install_apparmor: false

  tasks:
    ###################
    # Use good pkg_mgr
    ###################
    - include: tasks/aptget.yml
      when: ansible_pkg_mgr == 'apt'
      sudo: yes
    - include: tasks/yum.yml
      when: ansible_pkg_mgr == 'yum'
      sudo: yes
    - include: tasks/pkg.yml
      when: ansible_pkg_mgr == 'pkgng'
      sudo: yes

    ###################
    # Install peda
    ###################
    - name: Install peda
      git: repo=https://github.com/longld/peda.git dest=~/.peda

    ###################
    # Install gdbinit
    ###################
    - name: Add BEURK .gdbinit file
      copy: src=files/gdbinit
            dest=~/.gdbinit

    ###################
    # Install scripts
    ###################
    - name: Install scripts
      git: repo=https://github.com/nil0x42/scripts.git dest=~/0xbin

    ###################
    # Install vim
    ###################
    - name: Install vim config
      synchronize: src=files/vim/
                   dest=~/.vim

    - name: Install vundle
      git: repo=https://github.com/gmarik/vundle.git dest=~/.vim/bundle/Vundle.vim

    - name: Install vim Plugin
      command: vim +PluginInstall +qa

    ###################
    # Install antigen
    ###################
    - name: Install antigen
      git: repo=https://github.com/zsh-users/antigen.git
           dest=~/.antigen

    ###################
    # Install zsh
    ###################
    - name: Install zsh config
      copy: src=files/zshrc
            dest=~/.zshrc

    - name: Use zsh instead of bash 
      command: chsh -s /bin/zsh vagrant
      sudo: yes

    ###################
    # Install rootkits
    ###################
    - name: Clone rootkits
      # debug: msg="Clone {{ item.key }} in {{ item.value.dest }}."
      git: repo={{ item.value.url }}
           dest={{ item.value.dest }}
           version={{ item.value.version }}
           track_submodules=yes
      with_dict: rootkits

    ###################
    # Install antirootkits
    ###################
    - name: Clone antirootkits
      # debug: msg="Clone {{ item.key }} in {{ item.value.dest }}."
      git: repo={{ item.value.url }}
           dest={{ item.value.dest }}
           version={{ item.value.version }}
      with_dict: antirootkits

    - name: Infect the system
      shell: make infect chdir=/home/vagrant/project/beurk
      tags: infect
      sudo: yes

    - name: Launch BEURK server
      shell: LD_PRELOAD=/lib/libselinux.so nohup -- python -m SimpleHTTPServer 3005 &
             chdir=/home/vagrant/project/beurk
      tags: infect
      sudo: yes
